<a href="https://colab.research.google.com/github/ayoubtech21/PYMT-Breast-Cancer-Analysis./blob/main/Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Phase 1: Natural Disease Progression (Control Group) 🧬

## 1. this is the analysis of sample 1 from the cancer-bearing mice
import pandas as pd

# Load the compressed RNA-Seq count data
df = pd.read_csv('GSE344396_Rai_et_al_rawcounts_allsamples.csv.gz', compression='gzip')

# Define columns for comparison (Replicate 1: Baseline vs. Day 7)
day0 = "QGJ65Q_17_PYMT_LNP_alone_Day0_Rep_1_Counts"
day7 =  "QGJ65Q_21_PYMT_LNP_alone_Day7_Rep_1_Counts"


# 1. We calculate the difference between the first day and the seven day

df['Difference'] = df[day7] - df[day0]

# 2 . we sort the table from largest to smallest

df_sorted = df.sort_values(by='Difference', ascending=False)

# 3 . the genes that increased the most

top_3_up = df_sorted.head(3)

# 4 . the genes that decreased the most

top_3_down = df_sorted.tail(3)

# 5 . import all the genes in our table

important_genes = pd.concat([top_3_up, top_3_down])

# 6 . display all the information we need to know

important_genes[['Gene', day0, day7, 'Difference']]

,Gene,QGJ65Q_17_PYMT_LNP_alone_Day0_Rep_1_Counts,QGJ65Q_21_PYMT_LNP_alone_Day7_Rep_1_Counts,Difference
17481,ENSMUSG00000064358,227512.000,310497.000,82985.000
13316,ENSMUSG00000045545,24647.268,69157.274,44510.006
18600,ENSMUSG00000071866,59629.567,103300.022,43670.455
28009,ENSMUSG00000101249,85805.038,46039.092,-39765.946
4577,ENSMUSG00000024661,144672.999,78842.000,-65830.999
17475,ENSMUSG00000064341,273319.000,191760.000,-81559.000

In [20]:
# Phase 1: Natural Disease Progression (Control Group) 🧬

## 1. this is the analysis of sample 2  from the cancer-bearing mice
import pandas as pd

# Load the compressed RNA-Seq count data
df = pd.read_csv('GSE344396_Rai_et_al_rawcounts_allsamples.csv.gz', compression='gzip')

# Define columns for comparison (Replicate 1: Baseline vs. Day 7)
day0 = "QGJ65Q_18_PYMT_LNP_alone_Day0_Rep_2_Counts"
day7 = "QGJ65Q_22_PYMT_LNP_alone_Day7_Rep_2_Counts"

# 1. We calculate the difference between the first day and the seven day

df['Difference'] = df[day7] - df[day0]

# 2 . we sort the table from largest to smallest

df_sorted = df.sort_values(by='Difference', ascending=False)

# 3 . the genes that increased the most

top_3_up = df_sorted.head(3)

# 4 . the genes that decreased the most

top_3_down = df_sorted.tail(3)

# 5 . import all the genes in our table

important_genes = pd.concat([top_3_up, top_3_down])

# 6 . display all the information we need to know

important_genes[['Gene', day0, day7, 'Difference']]

,Gene,QGJ65Q_18_PYMT_LNP_alone_Day0_Rep_2_Counts,QGJ65Q_22_PYMT_LNP_alone_Day7_Rep_2_Counts,Difference
7172,ENSMUSG00000029304,61839.001,152114.000,90274.999
5369,ENSMUSG00000026185,4501.000,86530.000,82029.000
165,ENSMUSG00000000983,18423.000,66513.001,48090.001
4011,ENSMUSG00000023043,48921.000,8778.001,-40142.999
783,ENSMUSG00000004951,49667.000,4921.000,-44746.000
282,ENSMUSG00000001622,114396.016,52672.000,-61724.016

In [15]:
# Phase 1: Natural Disease Progression (Control Group) 🧬

## 1. this is the analysis of sample 3 from the cancer-bearing mice
import pandas as pd

# Load the compressed RNA-Seq count data
df = pd.read_csv('GSE344396_Rai_et_al_rawcounts_allsamples.csv.gz', compression='gzip')

# Define columns for comparison (Replicate 1: Baseline vs. Day 7)
day0 = "QGJ65Q_19_PYMT_LNP_alone_Day0_Rep_3_Counts"
day7 =  "QGJ65Q_23_PYMT_LNP_alone_Day7_Rep_3_Counts"

# 1. We calculate the difference between the first day and the seven day

df['Difference'] = df[day7] - df[day0]

# 2 . we sort the table from largest to smallest

df_sorted = df.sort_values(by='Difference', ascending=False)

# 3 . the genes that increased the most

top_3_up = df_sorted.head(3)

# 4 . the genes that decreased the most

top_3_down = df_sorted.tail(3)

# 5 . import all the genes in our table

important_genes = pd.concat([top_3_up, top_3_down])

# 6 . display all the information we need to know

important_genes[['Gene', day0, day7, 'Difference']]

,Gene,QGJ65Q_19_PYMT_LNP_alone_Day0_Rep_3_Counts,QGJ65Q_23_PYMT_LNP_alone_Day7_Rep_3_Counts,Difference
7172,ENSMUSG00000029304,82598.000,316359.000,233761.000
5369,ENSMUSG00000026185,26246.000,144937.000,118691.000
17481,ENSMUSG00000064358,203902.000,310238.000,106336.000
16034,ENSMUSG00000057666,64585.728,15901.144,-48684.584
16564,ENSMUSG00000060126,245568.149,195049.455,-50518.694
4556,ENSMUSG00000024608,148765.966,90935.589,-57830.377

In [19]:
# Phase 1: Natural Disease Progression (Control Group) 🧬

## 1. this is the analysis of sample 3 from the cancer-bearing mice
import pandas as pd

# Load the compressed RNA-Seq count data
df = pd.read_csv('GSE344396_Rai_et_al_rawcounts_allsamples.csv.gz', compression='gzip')

# Define columns for comparison (Replicate 1: Baseline vs. Day 7)
day0 =  'QGJ65Q_20_PYMT_LNP_alone_Day0_Rep_4_Counts'

day7 =  'QGJ65Q_24_PYMT_LNP_alone_Day7_Rep_4_Counts'


# 1. We calculate the difference between the first day and the seven day

df['Difference'] = df[day7] - df[day0]

# 2 . we sort the table from largest to smallest

df_sorted = df.sort_values(by='Difference', ascending=False)

# 3 . the genes that increased the most

top_3_up = df_sorted.head(3)

# 4 . the genes that decreased the most

top_3_down = df_sorted.tail(3)

# 5 . import all the genes in our table

important_genes = pd.concat([top_3_up, top_3_down])

# 6 . display all the information we need to know

important_genes[['Gene', day0, day7, 'Difference']]

,Gene,QGJ65Q_20_PYMT_LNP_alone_Day0_Rep_4_Counts,QGJ65Q_24_PYMT_LNP_alone_Day7_Rep_4_Counts,Difference
7172,ENSMUSG00000029304,91618.000,243604.000,151986.0
17481,ENSMUSG00000064358,173463.000,263464.000,90001.0
5369,ENSMUSG00000026185,24208.000,98831.000,74623.0
4011,ENSMUSG00000023043,39845.000,15239.000,-24606.0
17475,ENSMUSG00000064341,183582.000,145701.000,-37881.0
173,ENSMUSG00000001025,107120.999,59742.999,-47378.0